# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentcollision < Formula
  desc "Coordination daemon for parallel AI coding agents"
  homepage "https://github.com/agentcollision/agentcollision"
  version "0.8.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentcollision/agentcollision/releases/download/v0.8.2/agentcollision_0.8.2_darwin_amd64.tar.gz"
      sha256 "f412a2d46bbc794c74229833789cc060c081a2dc595f54ce74f8a65bb32d36d9"

      define_method(:install) do
        bin.install "agentcollision"
        bin.install_symlink "agentcollision" => "ac"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentcollision/agentcollision/releases/download/v0.8.2/agentcollision_0.8.2_darwin_arm64.tar.gz"
      sha256 "254b9e9bc9d5da30279847e56fe1ea8b0ce6910eb4401abf514948cdb44bb94f"

      define_method(:install) do
        bin.install "agentcollision"
        bin.install_symlink "agentcollision" => "ac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentcollision/agentcollision/releases/download/v0.8.2/agentcollision_0.8.2_linux_amd64.tar.gz"
      sha256 "d7e89fbbbd5d0c7bbd29e6bf5ce0930ec7b129a5b0068382ff8d1417c6b8085b"
      define_method(:install) do
        bin.install "agentcollision"
        bin.install_symlink "agentcollision" => "ac"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentcollision/agentcollision/releases/download/v0.8.2/agentcollision_0.8.2_linux_arm64.tar.gz"
      sha256 "5ef9349f30033b87d2db8aac9e14225e342dcf96247b0d40131c9cbe34db6c14"
      define_method(:install) do
        bin.install "agentcollision"
        bin.install_symlink "agentcollision" => "ac"
      end
    end
  end

  def post_install
    # Auto-restart the AgentCollision daemon after upgrade so the new
    # binary's in-memory state (matcher, sweeper, classifier) picks
    # up whatever fixes shipped in this release. Before alpha.11
    # users had to manually run `launchctl kickstart -k ...` after
    # every `brew upgrade`, and the mismatch between the on-disk
    # binary and the running daemon process caused hard-to-diagnose
    # "why isn't my fix active" incidents. See bug #7 in
    # docs/internals/v0.4/known-bugs-post-alpha.7.md.
    #
    # Only does anything if the launchd service is already loaded
    # (i.e. the user previously ran `ab init` and opted into
    # autostart). On a fresh install, the service isn't registered
    # and the kickstart silently no-ops — `ab init` will wire up
    # autostart when the user runs it.
    #
    # alpha.14 fix: alpha.11–alpha.13 used Ruby's `system` with the
    # `err: File::NULL` keyword, which makes Homebrew echo the
    # entire call (including the Ruby keyword args) to the user as
    # `==> launchctl kickstart -k ... {err: "/dev/null"}`. Ugly.
    # `quiet_system` suppresses the echo, and we route stderr
    # through a shell redirect inside a single argv string so no
    # Ruby keywords leak into Homebrew's output.
    if OS.mac?
      # Restart the new-name service if registered.
      quiet_system "/bin/sh", "-c",
        "launchctl kickstart -k gui/$(id -u)/com.agentcollision.daemon 2>/dev/null || true"
      # Also kick the legacy agentberth service for users upgrading
      # from pre-rename installs. Their plist is still
      # com.agentberth.daemon until they re-run `ac init`, and we
      # want their next tool call to use the NEW binary even if
      # they haven't re-run init yet.
      quiet_system "/bin/sh", "-c",
        "launchctl kickstart -k gui/$(id -u)/com.agentberth.daemon 2>/dev/null || true"
    end
  end

  def caveats
    <<~EOS
      AgentCollision #{version} installed.

      First-time setup:
        ac init        # detect AI tools, install hooks, optional autostart

      Upgrading from agentberth?
        ac init        # rewrites your hooks + launchd plist for the new name
        Your old ~/.agentberth/ data is migrated automatically on first run.

      What's new in this version:
        https://github.com/agentcollision/agentcollision/blob/main/CHANGELOG.md

      Dashboard (after `ac init`):
        http://localhost:7777/ui/

      Quick start:
        https://github.com/agentcollision/agentcollision/blob/main/docs/00-for-first-time-users.md
    EOS
  end

  test do
    system "#{bin}/agentcollision", "version"
  end
end
