# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentcollision < Formula
  desc "Coordination daemon for parallel AI coding agents"
  homepage "https://github.com/agentcollision/agentcollision"
  version "0.17.12"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.agentcollision.com/v0.17.12/agentcollision_0.17.12_darwin_amd64.tar.gz"
      sha256 "5627ed92dd90ee72ca3ddfca6be362d74ecd2764cbdbf3cdeb916989ee853adc"

      define_method(:install) do
        bin.install "agentcollision"
        bin.install_symlink "agentcollision" => "agc"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.agentcollision.com/v0.17.12/agentcollision_0.17.12_darwin_arm64.tar.gz"
      sha256 "24d4a05ae4c45d7c5e60181895b4a3698834abf59627260ff0fd54a5be1f520b"

      define_method(:install) do
        bin.install "agentcollision"
        bin.install_symlink "agentcollision" => "agc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.agentcollision.com/v0.17.12/agentcollision_0.17.12_linux_amd64.tar.gz"
      sha256 "ce5438aca50d0ecbdecb8bb8cc8a65fbd5fbc4da9d31e416418cd64c5539ba8b"
      define_method(:install) do
        bin.install "agentcollision"
        bin.install_symlink "agentcollision" => "agc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.agentcollision.com/v0.17.12/agentcollision_0.17.12_linux_arm64.tar.gz"
      sha256 "0ba81608cb954875b1f1a29bd49648d2ed2ab74c8222e5231f2a6962a84c8659"
      define_method(:install) do
        bin.install "agentcollision"
        bin.install_symlink "agentcollision" => "agc"
      end
    end
  end

  def post_install
    # Auto-restart the AgentCollision daemon after upgrade so the new
    # binary's in-memory state (matcher, sweeper, classifier) picks
    # up whatever fixes shipped in this release. Before alpha.11
    # users had to manually run `launchctl kickstart -k ...` after
    # every `brew upgrade`; the mismatch between the on-disk binary
    # and the running daemon process caused hard-to-diagnose "why
    # isn't my fix active" incidents.
    #
    # v0.14.2: replaced the inline `launchctl kickstart -k` with
    # `agc heal`. kickstart silently failed in several launchd
    # domain edge cases (de-registered service, stale socket, zombie
    # PID holding the unix socket) which we hit in production.
    # `agc heal` does the full diagnose-and-fix flow: probe state,
    # SIGTERM/SIGKILL the running process if any, remove stale
    # socket, `launchctl bootout` + `bootstrap` the plist, wait for
    # /v1/info to confirm the new version is up. Idempotent.
    #
    # --quiet suppresses success chatter so brew output stays clean;
    # diagnostic + error output still surfaces on failure so a broken
    # upgrade is visible.
    if OS.mac?
      quiet_system "/bin/sh", "-c",
        "#{bin}/agc heal --quiet 2>/dev/null || true"

      # Rewrite Claude Code hook command paths to point at the new
      # cellar version. Pre-2026-04-25 (v0.11.6 and earlier) baked the
      # versioned cellar path into ~/.claude/settings.json on init —
      # `brew upgrade` then deleted the old cellar path, breaking
      # every hook silently. agc rewrite-hooks is idempotent and uses
      # the version-stable symlink resolver so future upgrades survive.
      # Best-effort: if the user has never run agc init (no
      # ~/.claude/settings.json), the command no-ops.
      quiet_system "/bin/sh", "-c",
        "#{bin}/agc rewrite-hooks --quiet 2>/dev/null || true"
    end
  end

  def caveats
    <<~EOS
      AgentCollision #{version} installed.

      First-time setup:
        agc init        # detect AI tools, install hooks, optional autostart
        agc login       # connect this machine to your account (opens browser)

      What's new in this version:
        https://github.com/agentcollision/agentcollision/blob/main/CHANGELOG.md

      Dashboard (after `agc init`):
        http://localhost:7777/ui/

      Quick start:
        https://github.com/agentcollision/agentcollision/blob/main/docs/00-for-first-time-users.md
    EOS
  end

  test do
    system "#{bin}/agentcollision", "version"
  end
end
