# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentcollision < Formula
  desc "Coordination daemon for parallel AI coding agents"
  homepage "https://github.com/agentcollision/agentcollision"
  version "0.9.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentcollision/agentcollision/releases/download/v0.9.4/agentcollision_0.9.4_darwin_amd64.tar.gz"
      sha256 "624bfb9df2cc3e55a0dcb22e2b97273d09c1645e932e68f2b075fb96d8bc5969"

      define_method(:install) do
        bin.install "agentcollision"
        bin.install_symlink "agentcollision" => "ac"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentcollision/agentcollision/releases/download/v0.9.4/agentcollision_0.9.4_darwin_arm64.tar.gz"
      sha256 "9aca6b7c04ea0277277db38f4c375ff96c9f56a9823bd4d0b0f471a07170346e"

      define_method(:install) do
        bin.install "agentcollision"
        bin.install_symlink "agentcollision" => "ac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentcollision/agentcollision/releases/download/v0.9.4/agentcollision_0.9.4_linux_amd64.tar.gz"
      sha256 "e8d83bfb791887ee75623884bb06e770a42788a58a80ebcf96c9456c816a25a4"
      define_method(:install) do
        bin.install "agentcollision"
        bin.install_symlink "agentcollision" => "ac"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentcollision/agentcollision/releases/download/v0.9.4/agentcollision_0.9.4_linux_arm64.tar.gz"
      sha256 "3d038283060b7843782ce3822b7feecaf9f0dbed0bf9d77b705b74eb28bac429"
      define_method(:install) do
        bin.install "agentcollision"
        bin.install_symlink "agentcollision" => "ac"
      end
    end
  end

  def post_install
    # Auto-restart the AgentCollision daemon after upgrade so the new
    # binary's in-memory state (matcher, sweeper, classifier) picks
    # up whatever fixes shipped in this release. Before alpha.11
    # users had to manually run `launchctl kickstart -k ...` after
    # every `brew upgrade`, and the mismatch between the on-disk
    # binary and the running daemon process caused hard-to-diagnose
    # "why isn't my fix active" incidents. See bug #7 in
    # docs/internals/v0.4/known-bugs-post-alpha.7.md.
    #
    # Only does anything if the launchd service is already loaded
    # (i.e. the user previously ran `ab init` and opted into
    # autostart). On a fresh install, the service isn't registered
    # and the kickstart silently no-ops — `ab init` will wire up
    # autostart when the user runs it.
    #
    # alpha.14 fix: alpha.11–alpha.13 used Ruby's `system` with the
    # `err: File::NULL` keyword, which makes Homebrew echo the
    # entire call (including the Ruby keyword args) to the user as
    # `==> launchctl kickstart -k ... {err: "/dev/null"}`. Ugly.
    # `quiet_system` suppresses the echo, and we route stderr
    # through a shell redirect inside a single argv string so no
    # Ruby keywords leak into Homebrew's output.
    if OS.mac?
      # Restart the new-name service if registered.
      quiet_system "/bin/sh", "-c",
        "launchctl kickstart -k gui/$(id -u)/com.agentcollision.daemon 2>/dev/null || true"
      # Also kick the legacy agentberth service for users upgrading
      # from pre-rename installs. Their plist is still
      # com.agentberth.daemon until they re-run `ac init`, and we
      # want their next tool call to use the NEW binary even if
      # they haven't re-run init yet.
      quiet_system "/bin/sh", "-c",
        "launchctl kickstart -k gui/$(id -u)/com.agentberth.daemon 2>/dev/null || true"
    end
  end

  def caveats
    <<~EOS
      AgentCollision #{version} installed.

      First-time setup:
        ac init        # detect AI tools, install hooks, optional autostart

      Upgrading from agentberth?
        ac init        # rewrites your hooks + launchd plist for the new name
        Your old ~/.agentberth/ data is migrated automatically on first run.

      What's new in this version:
        https://github.com/agentcollision/agentcollision/blob/main/CHANGELOG.md

      Dashboard (after `ac init`):
        http://localhost:7777/ui/

      Quick start:
        https://github.com/agentcollision/agentcollision/blob/main/docs/00-for-first-time-users.md
    EOS
  end

  test do
    system "#{bin}/agentcollision", "version"
  end
end
